---
# By default egress traffic is not allowed, define below the ports allowed.
ingress:
- ports:
  - protocol: TCP
    port: 443
  - protocol: TCP
    port: 80
  - protocol: TCP
    port: 3000
  - protocol: TCP
    port: 22
  - protocol: TCP
    port: 5986
  - protocol: TCP
    port: 3389
  - protocol: TCP
    port: 2181
  - protocol: TCP
    port: 9092
  - protocol: TCP
    port: 2001
  - protocol: TCP
    port: 2002
  - protocol: TCP
    port: 2003
egress:
- ports:
  - protocol: TCP
    port: 443
  - protocol: TCP
    port: 80
  - protocol: TCP
    port: 3000
  - protocol: TCP
    port: 22
  - protocol: TCP
    port: 5986
  - protocol: TCP
    port: 3389
  - protocol: TCP
    port: 2181
  - protocol: TCP
    port: 9092
  - protocol: TCP
    port: 2001
  - protocol: TCP
    port: 2002
  - protocol: TCP
    port: 2003
